language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install pylint
  - pip install radon
  - pip install python-coveralls
  
# command to run tests
script:
  - pylint actuator.py
  - radon cc actuator.py -a -s
  - radon raw actuator.py
  - radon mi actuator.py -s
  - python actuator_test.py
  - coverage run --source=actuator actuator_test.py
  - coveralls

after_success:
  - coveralls